spring:
  profiles:
    active: development
---

spring:
  profiles: development
  cloud:
    config:
      server:
        git:
          uri: https://github.com/beatific/microservice-config
server:
  port: 8888
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: configserver
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
